GrabGrub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Kiosk.urls'))
]

Kiosk/urls.py
from django.urls import path
from . import views
from .views import homepage, customerlist, customerform, foodlist, vieworders, deleteorder,editordersform,addordersform

urlpatterns=[
    path('grabgrub', views.homepage, name='homepage'),
    path('grabgrub/viewcustomers.html/',views.customerlist,name='customerlist'),
    path('grabgrub/customer.html/',views.customerform,name='customerform'),
    path('<int:id>/customer', views.customerform,name="customerupdate"),
    path('<int:pk>/customerorder', views.customerorder,name="customerorder"),
    path('grabgrub/viewfood.html/', views.foodlist,name="foodlist"),
    path('grabgrub/food.html/',views.foodform,name='foodform'),
    path('<int:id>/food', views.foodform,name="foodupdate"),
    path('grabgrub/vieworders.html/',views.vieworders,name='vieworders'),
    path('grabgrub/order.html/',views.addordersform,name='orderform'),
    path('order/<int:pk>', views.editordersform,name="editordersform"),
    path('delete/<int:pk>', views.deleteorder,name='deleteorder'),
]

Kiosk/models.py
from django.db import models
# models.ForeignKey(Supplier, on_delete = models.CASCADE)
# Create your models here.

class Food(models.Model):
    name = models.CharField(max_length=300)
    description = models.CharField(max_length=300)
    price = models.FloatField()
    created_at = models.DateTimeField(blank = True, null = True)
    objects = models.Manager()

    def getName(self):
        return self.name
    
    def getDesc(self):
        return self.description

    def getPrice(self):
        return self.price

    def __str__(self):
        return str(self.pk)+": "+self.name+" - "+str(self.price)+", "+self.description+" created at: "+str(self.created_at)

class Customer(models.Model):
    name = models.CharField(max_length=300)
    address = models.CharField(max_length=300)
    city = models.CharField(max_length=300)
    objects = models.Manager()


    def getName(self):
        return self.name

    def getAddress(self):
        return self.address

    def getCity(self):
        return self.city

    def __str__(self):
        return str(self.pk)+": "+self.name+" - "+self.address+", "+self.city

class Order(models.Model):
    ordered_at = models.DateTimeField(auto_now_add=True,blank = True, null = True)
    mode_payment = models.CharField(max_length=300)
    cust_order = models.ForeignKey(Customer, on_delete = models.CASCADE)
    objects = models.Manager()

    def getMode(self):
        return self.mode_payment


    def __str__(self):
        return str(self.pk)+": "+self.cust_order.name+", "+self.cust_order.address+", "+self.cust_order.city+", "+self.mode_payment+", ordered at "+str(self.ordered_at)


class OrderLine(models.Model):
    ORD = models.ForeignKey(Order, on_delete = models.CASCADE)
    food = models.ForeignKey(Food, on_delete = models.CASCADE)
    quantity = models.FloatField()
    objects = models.Manager()

    def getQuantity(self):
        return self.quantity

    def solver(self):
        total = self.quantity * self.food.price
        return total

    def __str__(self):
        return str(self.pk)+": "+str(self.ORD.pk)+" - "+self.food.name+str(self.quantity)
    
    

Kiosk/forms.py
from django import forms
from .models import Customer,Food,OrderLine,Order

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields='__all__'

class FoodForm(forms.ModelForm):
    class Meta:
        model = Food
        fields='name','description','price'


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields='cust_order','mode_payment'

class OrderLineForm(forms.ModelForm):
    class Meta:
        model = OrderLine
        fields=('food','quantity')

    #def __init__(self, *args, **kwargs):
        #super(OrderLineForm, self).__init__(*args, **kwargs)
        #self.fields['cust_order']=forms.MultipleChoiceField(queryset=Order.objects.filter())
    

Kiosk/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.shortcuts import HttpResponse
from .models import Food,Customer,Order,OrderLine
from .forms import CustomerForm, FoodForm, OrderLineForm,OrderForm
# Create your views here.

def homepage(request):
    return render(request,'Kiosk/home.html')

def customerlist(request):
    customer_objects = Customer.objects.all()
    return render(request,'Kiosk/CUSTOMER/customer_list.html',{'customers':customer_objects})

def foodlist(request):
    food_objects=Food.objects.all()
    return render(request,'Kiosk/FOOD/food_list.html',{'foods':food_objects}) 

def customerorder(request,pk):
    customer = OrderLine.objects.filter(ORD__cust_order__pk=pk)
    cust_order = Customer.objects.get(pk=pk)
    c_obj = get_object_or_404(Customer, pk=pk)
    gtotal = sum( d.solver() for d in OrderLine.objects.filter(ORD__cust_order__name = cust_order.name))
    return render(request,'Kiosk/CUSTOMER/customerorder.html',{'customer':customer,'c_obj':c_obj,'gtotal':gtotal,'cust_order':cust_order})


def vieworders(request):
    orderline_objects=OrderLine.objects.all()
    return render(request,'Kiosk/ORDER/order_list.html',{'orderline_objects':orderline_objects,})


def addordersform(request):
    customer_objects=Customer.objects.all()
    food_objects=Food.objects.all()
    if(request.method=='POST'):
        nCustomerOrder = request.POST.get('CustomerName')
        nPayment = request.POST.get('PaymentType')
        nFood = request.POST.get('food')
        nQuant = request.POST.get('quantity')
        nOrder = Order.objects.create(cust_order=Customer.objects.get(pk=nCustomerOrder),mode_payment= nPayment)
        OrderLine.objects.create(ORD=nOrder,food=Food.objects.get(pk=nFood),quantity=nQuant)
        return redirect('vieworders')
    else:
        return render(request,'Kiosk/ORDER/addorder.html',{'c':customer_objects,'f':food_objects})

def deleteorder(request,pk):
    Order.objects.filter(pk=pk).delete()
    OrderLine.objects.filter(pk=pk).delete()
    return redirect('vieworders')

def editordersform(request,pk):
    customer_objects=Customer.objects.all()
    food_objects = Food.objects.all()
    order_objects = Order.objects.all()
    if(request.method=='POST'):
        nPayment = request.POST.get('PaymentType')
        nFood = request.POST.get('food')
        nQuantity = request.POST.get('quantity')
        Order.objects.filter(pk=pk).update(mode_payment=nPayment)
        OrderLine.objects.filter(pk=pk).update(ORD=Order.objects.get(pk=pk),food=Food.objects.get(pk=nFood),quantity=nQuantity)
        return redirect('vieworders')
    else:
        o = get_object_or_404(OrderLine,pk=pk)
        return render(request, 'Kiosk/ORDER/editorder.html',{'o':o,'c':customer_objects,'f':food_objects, 'Order':order_objects})

def customerform(request,id=0):
    if request.method == "GET":
        if id==0:
            customer_form = CustomerForm()
        else:
            customer = Customer.objects.get(pk=id)
            customer_form = CustomerForm(instance=customer)
        return render(request,'Kiosk/CUSTOMER/addcustomer.html',{'cform':customer_form})
    else:
        if id==0:
            customer_form = CustomerForm(request.POST)
        else:            
            customer = Customer.objects.get(pk=id)
            customer_form = CustomerForm(request.POST,instance=customer)
        if customer_form.is_valid():
            customer_form.save()
        return redirect('/grabgrub/viewcustomers.html')

def foodform(request,id=0):
    if request.method == "GET":
        if id==0:
            food_form = FoodForm()
        else:
            food = Food.objects.get(pk=id)
            food_form = FoodForm(instance=food)
        return render(request,'Kiosk/FOOD/addfood.html',{'fform':food_form})
    else:
        if id==0:
            food_form = FoodForm(request.POST)
        else:            
            food = Food.objects.get(pk=id)
            food_form = FoodForm(request.POST,instance=food)
        if food_form.is_valid():
            food_form.save()
        return redirect('/grabgrub/viewfood.html')

Kiosk/templates/Kiosk/CUSTOMER/addcustomer.html
{% extends 'Kiosk/home.html' %}
{% load static %}

    {% block content %}
    <form action='' method='post' autocomplete="off">
        <div class="jumbotron">
            <h1 class="display-4">Customer Entry / Update</h1>
            <p class="lead">Add / Update a Customer.</p>
            <hr class="my-4">
            <p>Please complete the form below.</p>
                <input type="hidden" name="csrfmiddlewaretoken" value="2WEgGovnMfrXY6vJLpY2tAGXsJigJXKVojYX2ryhXCET0bEaLhIr0MN7zhgFqyGD">    

        <div id="div_id_name" class="form-group"> 
            <label for="id_name" class=" requiredField">
                Name<span class="asteriskField">*</span> 
            </label> 
            <div class=""> 
                <input type="text" name="name" maxlength="300" class="textinput textInput form-control" required="" id="id_name"> 
            </div> 
        </div> 
        <div id="div_id_address" class="form-group"> 
            <label for="id_address" class=" requiredField">
                Address<span class="asteriskField">*</span> 
            </label> 
            <div class=""> 
                <input type="text" name="address" maxlength="300" class="textinput textInput form-control" required="" id="id_address"> 
            </div> 
        </div> 
        <div id="div_id_city" class="form-group"> 
            <label for="id_city" class=" requiredField">
                City<span class="asteriskField">*</span> 
            </label>
             <div class=""> 
                 <input type="text" name="city" maxlength="300" class="textinput textInput form-control" required="" id="id_city"> 
                </div> 
            </div>
        
                <button type='submit' class="btn btn-secondary btn-lg btn-block">Add / Edit Customer</button>
                <br>
                <br>
                <a href="{% url 'homepage' %}"><button type="button" class="btn btn-secondary btn-lg btn-block">Back To Main</button></a>
        </div>
            </div>
            {% csrf_token %}
    </form>
    {% endblock %}

Kiosk/templates/Kiosk/CUSTOMER/customer_list.html
{% extends 'Kiosk/home.html' %}
{% load static %}


    {% block content %}
    <title>Grab Grub!</title>
    <br>
    <br>
    <h2 class="text-center">View All Customers</h2>
    <br>
    <br>
    <div class="container">
        <div class="row">


            <div class="col-12">

                <table class="table table-striped">
                    <thead>
                        <th scope="col"> Name </th>
                        <th scope="col"> Address </th>
                        <th scope="col"> City </th>
                        <th scope="col"> Actions </th>
                        <th>     </th>
                    </thead>
                    <tbody>
                        {% for c in customers %}
                        <tr>
                            <td> {{ c.name }} </td>
                            <td> {{ c.address }} </td>
                            <td> {{ c.city }} </td>
                            <td> <a href="{% url 'customerupdate' c.id %}"> Edit </a></td>
                            <td> <a href="{% url 'customerorder' pk=c.id %}"> View All Orders </a></td>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
    <div class='container'>
        <div class='row'>
            <div class="col-lg-6 offset-lg-3"> 
                <a href="{% url 'customerform' %}"><button id="singlebutton" name="singlebutton" class="btn btn-secondary btn-md btn-block">Add Customer</button></a>
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>
    <div class='container'>
        <div class='row'>
            <div class="col-lg-6 offset-lg-3"> 
                <a href="{% url 'homepage' %}"><button id="singlebutton" name="singlebutton" class="btn btn-secondary btn-md btn-block">Back to Main</button></a>
            </div>
        </div>
    </div>
        
    {% endblock %} 

Kiosk/templates/Kiosk/CUSTOMER/customerorder.html
{% extends 'Kiosk/home.html' %}
{% load static %}


    {% block content %}
    <title>Grab Grub!</title>
    <br>
    <br>
    <div class="jumbotron">
        <h1 class="display-4">View All Orders of {{ c_obj.name }}</h1>
        <p>Total Order bill is: PHP {{ gtotal }}</p>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <table class="table table-striped">
                        <thead>
                            <th scope="col"> Order Number </th>
                            <th scope="col"> Ordered By </th>
                            <th scope="col"> Total </th>
                            <th scope="col"> Ordered At </th>
                            <th>     </th>
                        </thead>
                        <tbody>
                            {% for c in customer %}
                            <tr>
                                <td> {{ c.pk }} </td>
                                <td> {{ c.ORD.cust_order.name }} </td>
                                <td> {{ c.solver }} </td>
                                <td> {{ c.ORD.ordered_at}} </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
        <br>
        <br>
        <br>
        <div class='container'>
            <div class='row'>
                <div class="col-lg-6 offset-lg-3"> 
                    <a href="{% url 'homepage' %}"><button id="singlebutton" name="singlebutton" class="btn btn-secondary btn-md btn-block">Back to Main</button></a>
                </div>
            </div>
        </div>
    </div>
        
    {% endblock %} 

Kiosk/templates/Kiosk/FOOD/addfood.html
{% extends 'Kiosk/home.html' %}
{% load static %}

    {% block content %}            
       
    <form action='' method='post' autocomplete="off">
        <div class="jumbotron">
            <h1 class="display-4">Food Entry / Update</h1>
            <p class="lead">Add / Update a Food Item.</p>
            <hr class="my-4">
            <p>Please complete the form below.</p>
                <input type="hidden" name="csrfmiddlewaretoken" value="r1xprejYguEsWCj4LCoIEBhaUUmbUmQYNoR6NhmSrRRoYHsvLu87bNok1skABXMG">
            
            <div id="div_id_name" class="form-group"> 
                <label for="id_name" class=" requiredField">
                    Name<span class="asteriskField">*</span> 
                </label> 
                <div class=""> 
                    <input type="text" name="name" maxlength="300" class="textinput textInput form-control" required="" id="id_name">
                </div> 
            </div> 
            <div id="div_id_description" class="form-group"> 
                <label for="id_description" class=" requiredField">
                    Description<span class="asteriskField">*</span> 
                </label> 
                <div class=""> 
                    <input type="text" name="description" maxlength="300" class="textinput textInput form-control" required="" id="id_description"> 
                </div> 
            </div> 
            <div id="div_id_price" class="form-group"> 
                <label for="id_price" class=" requiredField">
                    Price<span class="asteriskField">*</span> 
                </label> 
                <div class="">
                    <input type="number" name="price" step="any" class="numberinput form-control" required="" id="id_price"> 
                </div> 
            </div>

                <button type='submit' class="btn btn-secondary btn-lg btn-block">Add / Edit Food</button>
                <br>
                <br>
                <a href="{% url 'homepage' %}"><button type="button" class="btn btn-secondary btn-lg btn-block">Back To Main</button></a>
        </div>
        {% csrf_token %}
    </form>
    {% endblock %}

Kiosk/templates/Kiosk/FOOD/food_list.html
{% extends 'Kiosk/home.html' %}
{% load static %}


    {% block content %}
    <title>Grab Grub!</title>
    <br>
    <br>
    <h2 class="text-center">View All Food</h2>
    <br>
    <br>
    <div class="container">
        <div class="row">


            <div class="col-12">

                <table class="table table-striped">
                    <thead>
                        <th scope="col"> Name </th>
                        <th scope="col"> Description </th>
                        <th scope="col"> Price </th>
                        <th scope="col"> Actions </th>
                        <th>     </th>
                    </thead>
                    <tbody>
                        {% for f in foods %}
                        <tr>
                            <td> {{ f.name }} </td>
                            <td> {{ f.description }} </td>
                            <td> {{ f.price }} </td>
                            <td> <a href="{% url 'foodupdate' f.id %}"> Edit </a></td>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
    <div class='container'>
        <div class='row'>
            <div class="col-lg-6 offset-lg-3"> 
                <a href="{% url 'foodform' %}"><button id="singlebutton" name="singlebutton" class="btn btn-secondary btn-md btn-block">Add Food</button></a>
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>
    <div class='container'>
        <div class='row'>
            <div class="col-lg-6 offset-lg-3"> 
                <a href="{% url 'homepage' %}"><button id="singlebutton" name="singlebutton" class="btn btn-secondary btn-md btn-block">Back to Main</button></a>
            </div>
        </div>
    </div>
        
    {% endblock %} 

Kiosk/templates/Kiosk/ORDER/addorder.html
{% extends 'Kiosk/home.html' %}
{% load static %}


    {% block content %}            
    <form action="{% url 'orderform' %}" method='post' autocomplete="off">
            <div class="jumbotron">
                <h1 class="display-4">Order Entry / Update</h1>
                <p class="lead">Add / Update an Order.</p>
                <hr class="my-4">
                <p>Please complete the form below.</p>
                    <input type="hidden" name="csrfmiddlewaretoken" value="r1xprejYguEsWCj4LCoIEBhaUUmbUmQYNoR6NhmSrRRoYHsvLu87bNok1skABXMG">
    
                    <input type="hidden" name="csrfmiddlewaretoken" value="aaNHo1ie68VPFeJJGet4UFBGJ2p5Qagcwx7oK4l8hv8LHjSaG6dtrRIQQAnuxLcU">
                    
                

            <div id="div_id_cust_order" class="form-group"> <label for="id_cust_order" class=" requiredField">
                        Customer Name<span class="asteriskField">*</span> </label> <div class=""> <select name="CustomerName" class="select form-control" required="" id="CustomerName"> <option value="" selected="">---------</option> 
                            {% for c in c %}
                            <option value="{{c.pk}}">{{c.name}}</option> 
                            {% endfor %}
                        </select> 
                                
        
            <div id="div_id_food" class="form-group"> <label for="food" class=" requiredField">
                        Food<span class="asteriskField">*</span> </label> <div class=""> <select name="food" class="select form-control" required="" id="food"> <option value="" selected="">---------</option> 
                            {% for f in f %}
                            <option value="{{f.pk}}">{{f.name}}</option>
                            {% endfor %}        

            </select> </div> </div> <div id="div_id_quantity" class="form-group"> <label for="quantity" class=" requiredField">
                        Quantity<span class="asteriskField">*</span> </label> <div class=""> <input type="number" name="quantity" step="any" class="numberinput form-control" required="" id="quantity"> </div> </div>

            
            <input type='radio' id='PaymentType' name='PaymentType' value='Cash'>
            <label for='Cash'>Cash</label>

            <input type='radio' id='PaymentType' name='PaymentType' value='Card'>
            <label for='Card'>Card</label>


                <button type="submit" class="btn btn-secondary btn-lg btn-block">Add / Edit Order</button>
                <br>
                <br>
                <a href="/grabgrub"><button type="button" class="btn btn-secondary btn-lg btn-block">Back To Main</button></a>
            </div>
            {% csrf_token %}
    </form>
                
             
    {% endblock %}

Kiosk/templates/Kiosk/ORDER/editorder.html
{% extends 'Kiosk/home.html' %}
{% load static %}


    {% block content %}            
    <form action="{% url 'editordersform' pk=o.pk %}" method='POST' autocomplete="off">
            <div class="jumbotron">
                <h1 class="display-4">Order Entry / Update</h1>
                <p class="lead">Add / Update an Order.</p>
                <hr class="my-4">
                <p>Please complete the form below.</p>
                    <input type="hidden" name="csrfmiddlewaretoken" value="r1xprejYguEsWCj4LCoIEBhaUUmbUmQYNoR6NhmSrRRoYHsvLu87bNok1skABXMG">
    
                    <input type="hidden" name="csrfmiddlewaretoken" value="aaNHo1ie68VPFeJJGet4UFBGJ2p5Qagcwx7oK4l8hv8LHjSaG6dtrRIQQAnuxLcU">
                    
                

            <div id="div_id_cust_order" class="form-group"> <label for="id_cust_order" class=" requiredField">
                        Customer Name<span class="asteriskField">*</span> </label> <div class=""> <select name="CustomerName" class="select form-control" required="" id="CustomerName"> <option value="" selected="">---------</option> 
                            {% for c in c %}
                            <option value="{{c.pk}}">{{c.name}}</option> 
                            {% endfor %}
                        </select> 
                                
        
            <div id="div_id_food" class="form-group"> <label for="food" class=" requiredField">
                        Food<span class="asteriskField">*</span> </label> <div class=""> <select name="food" class="select form-control" required="" id="food"> <option value="" selected="">---------</option> 
                            {% for f in f %}
                            <option value="{{f.pk}}">{{f.name}}</option>
                            {% endfor %}        

            </select> 
        </div> </div> <div id="div_id_quantity" class="form-group"> <label for="quantity" class=" requiredField">
                        Quantity<span class="asteriskField">*</span> </label> <div class=""> <input type="number" name="quantity" step="any" class="numberinput form-control" required="" id="quantity"> </div> </div>

            
            <input type='radio' id='PaymentType' name='PaymentType' value='Cash'>
            <label for='Cash'>Cash</label>

            <input type='radio' id='PaymentType' name='PaymentType' value='Card'>
            <label for='Card'>Card</label>

            <form>
                <button type="submit" class="btn btn-secondary btn-lg btn-block">Add / Edit Order</button>
            </form>
                <br>
                <br>
                <a href="/grabgrub"><button type="button" class="btn btn-secondary btn-lg btn-block">Back To Main</button></a>
            </div>
            {% csrf_token %}
    </form>
                
             
    {% endblock %}

Kiosk/templates/Kiosk/ORDER/order_list.html
{% extends 'Kiosk/home.html' %}
{% load static %}


    {% block content %}
    <title>Grab Grub!</title>
    <br>
    <br>
    <h2 class="text-center">View All Orders</h2>
    <br>
    <br>
    <div class="container">
        <div class="row">


            <div class="col-12">

                <table class="table table-striped">
                    <thead>
                        <th scope="col"> Order Number </th>
                        <th scope="col"> Ordered By </th>
                        <th scope="col"> Total </th>
                        <th scope="col"> Mode of Payment </th>
                        <th>     </th>
                    </thead>
                    <tbody>
                        {% for o in orderline_objects %}
                        <tr>
                            <td> {{ o.pk }} </td>
                            <td> {{ o.ORD.cust_order.name }} </td>
                            <td> {{ o.solver }} </td>
                            <td> {{ o.ORD.mode_payment }}</td>
                            <td> 
                                <a href="{% url 'editordersform' pk=o.pk %}"> Edit </a>
                                <a href="{% url 'deleteorder' pk=o.pk %}"> Delete </a>
                            </td>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
    <div class='container'>
        <div class='row'>
            <div class="col-lg-6 offset-lg-3"> 
                <a href="{% url 'orderform' %}"><button id="singlebutton" name="singlebutton" class="btn btn-secondary btn-md btn-block">Add Order</button></a>
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>
    <div class='container'>
        <div class='row'>
            <div class="col-lg-6 offset-lg-3"> 
                <a href="{% url 'homepage' %}"><button id="singlebutton" name="singlebutton" class="btn btn-secondary btn-md btn-block">Back to Main</button></a>
            </div>
        </div>
    </div>
        
    {% endblock %} 

Kiosk/templates/Kiosk/home.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Grab Grub!</title>

  </head>

  <body>
    {% block content %}
     <div class='container'>
         <div class='col-md-10 offset-md-1 mt-5'>
            <div class="jumbotron">
                <h1 class="display-4">Grab Grub</h1>
                <p class="lead">Add, Delete, Edit your food orders below</p>
                <hr class="my-4">
                <a href="{% url 'customerlist' %}"><button type="button" class="btn btn-secondary btn-lg btn-block">View Customers</button></a>
                <br>
                <br>
                <a href="{% url 'foodlist' %}"><button type="button" class="btn btn-secondary btn-lg btn-block">View Food</button></a>
                <br>
                <br>
                <a href="{% url 'vieworders' %}"><button type="button" class="btn btn-secondary btn-lg btn-block">View Orders</button></a>
            </div>
         </div>
     </div>
     {% endblock %} 
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>